export default Object.freeze({

    FETCH_TODOS:         'FETCH_TODOS',
    FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
    FETCH_TODOS_FAIL:    'FETCH_TODOS_FAIL',

    CREATE_TODO:         'CREATE_TODO',
    CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
    CREATE_TODO_FAIL:    'CREATE_TODO_FAIL',

    COMPLETE_ALL_TODOS: 'COMPLETE_ALL_TODOS',

    COMPLETE:         'COMPLETE',
    COMPLETE_SUCCESS: 'COMPLETE_SUCCESS',
    COMPLETE_FAIL:    'COMPLETE_FAIL',

    CHANGE_PRIORITY:         'CHANGE_PRIORITY',
    CHANGE_PRIORITY_SUCCESS: 'CHANGE_PRIORITY_SUCCESS',
    CHANGE_PRIORITY_FAIL:    'CHANGE_PRIORITY_FAIL',

    DELETE_TODO:         'DELETE_TODO',
    DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
    DELETE_TODO_FAIL:    'DELETE_TODO_FAIL',

});
